name: VillageDefense
main: me.tomthedeveloper.Main
version: 3.0-ALPHA
softdepend: [WorldEdit, BarAPI]

commands:
  VillageDefense:
    description: All the commands!
    usage: /VD help
    permission: villagedefense.help
    aliases: [vd, villaged]
  #we gonna use only main command for every action

permissions:
  villagedefense.admin.*:
    children:
      villagedefense.admin.addsigns: true
      villagedefense.admin.smartreload: true
      villagedefense.admin.smartstop: true
      villagedefense.admin.setshopchest: true
      villagedefense.admin.setprice: true
